"""Prototype helpers for visible pixel injection in DICOM ultrasound previews."""

import math
import random
from pathlib import Path
from typing import Any

import numpy as np
import pydicom
from PIL import Image, ImageDraw, ImageFont
from pydicom.uid import ExplicitVRLittleEndian

# Conservative prototype-only angle set. This keeps annotation geometry easy to
# validate while still exercising rotated overlays.
ALLOWED_ROTATIONS_DEGREES: tuple[int, ...] = (0, 20, 90, 180, 270)

_DEFAULT_FONT_SIZE_PX: int = 18
_VALID_PLACEMENT_MODES: tuple[str, ...] = ("free", "corners")


def _resolve_font_size_px(font_size_pct: int) -> int:
    """Convert a font-size percentage to an absolute pixel size."""
    if font_size_pct < 1:
        raise ValueError("font_size_pct must be >= 1")
    return max(1, round(_DEFAULT_FONT_SIZE_PX * font_size_pct / 100))


def extract_preview_frame(ds: pydicom.Dataset) -> np.ndarray:
    """Return a 2D preview frame from a DICOM dataset.

    Args:
        ds: Loaded DICOM dataset.

    Returns:
        A 2D numpy array representing the first displayable frame.
    """
    pixel_array = np.asarray(ds.pixel_array)
    if pixel_array.ndim == 4:
        return pixel_array[0]
    if pixel_array.ndim == 3 and pixel_array.shape[-1] in {3, 4}:
        return pixel_array
    if pixel_array.ndim == 3:
        return pixel_array[0]
    return pixel_array


def normalize_to_uint8(frame: np.ndarray) -> np.ndarray:
    """Normalize a grayscale or RGB frame to uint8 for preview rendering."""
    array = np.asarray(frame)
    if array.dtype == np.uint8:
        return array

    working = array.astype(np.float32)
    min_value = float(np.min(working))
    max_value = float(np.max(working))
    if math.isclose(min_value, max_value):
        return np.zeros_like(array, dtype=np.uint8)

    normalized = (working - min_value) / (max_value - min_value)
    return np.clip(normalized * 255.0, 0, 255).astype(np.uint8)


def frame_to_image(frame: np.ndarray) -> Image.Image:
    """Convert a DICOM preview frame to a PIL image."""
    normalized = normalize_to_uint8(frame)
    if normalized.ndim == 2:
        return Image.fromarray(normalized, mode="L").convert("RGB")
    return Image.fromarray(normalized).convert("RGB")


def load_default_font(
    font_size_px: int = _DEFAULT_FONT_SIZE_PX,
) -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    """Load a font at the given pixel size. Falls back to the PIL default if Arial is unavailable."""
    try:
        return ImageFont.truetype("arial.ttf", size=font_size_px)
    except OSError:
        return ImageFont.load_default()


def build_visible_text_annotations(
    identity: dict[str, str],
    rotation_degrees: int = 0,
) -> list[dict[str, Any]]:
    """Create prototype overlay specs for the current echo/US example.

    Args:
        identity: Synthetic identity map as generated by ``identity.py``.
        rotation_degrees: Prototype rotation angle for all visible texts.

    Returns:
        A list of overlay spec dictionaries.

    Raises:
        ValueError: If the requested rotation is not part of the prototype set.
    """
    _validate_rotation(rotation_degrees)
    return [
        {
            "label": "PatientName",
            "text": identity["patient_name"],
            "region": "header_overlay",
            "line_index": 0,
            "rotation_degrees": rotation_degrees,
        },
        {
            "label": "PatientID",
            "text": identity["patient_id"],
            "region": "header_overlay",
            "line_index": 1,
            "rotation_degrees": rotation_degrees,
        },
        {
            "label": "AccessionNumber",
            "text": identity["accession_number"],
            "region": "header_overlay",
            "line_index": 2,
            "rotation_degrees": rotation_degrees,
        },
    ]


def render_visible_annotations(
    frame: np.ndarray,
    annotations: list[dict[str, Any]],
    font_size_px: int = _DEFAULT_FONT_SIZE_PX,
) -> tuple[Image.Image, list[dict[str, Any]]]:
    """Render prototype text overlays and return preview plus geometry records.

    Args:
        frame: DICOM preview frame.
        annotations: Overlay specs with ``text``, ``position``, and rotation.
        font_size_px: Absolute pixel size of the font to use.

    Returns:
        Tuple of rendered preview image and visible annotation metadata.
    """
    preview = frame_to_image(frame)
    font = load_default_font(font_size_px=font_size_px)
    render_records: list[dict[str, Any]] = []

    for annotation in annotations:
        preview, record = _render_single_annotation(preview, annotation, font)
        render_records.append(record)

    return preview, render_records


def render_annotations_for_dataset(
    ds: pydicom.Dataset,
    annotations: list[dict[str, Any]],
    font_size_px: int = _DEFAULT_FONT_SIZE_PX,
) -> tuple[Image.Image, list[dict[str, Any]]]:
    """Extract a DICOM preview frame and render visible prototype annotations."""
    return render_visible_annotations(
        extract_preview_frame(ds), annotations, font_size_px=font_size_px
    )


def save_preview_image(image: Image.Image, output_path: str | Path) -> Path:
    """Save a rendered preview image to disk."""
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination)
    return destination


def inject_visible_text(
    *,
    ds: pydicom.Dataset,
    visible_injections: list[dict[str, Any]],
    output_path: Path,
    preview_path: Path,
    seed: int,
    rotation_degrees: int,
    example_type: str,
    font_size_pct: int = 100,
    placement_mode: str = "corners",
) -> dict[str, Any]:
    """Render visible text into the dataset pixels and save a preview image.

    Args:
        ds: DICOM dataset to modify.
        visible_injections: Planned visible overlays from the orchestrator.
        output_path: Final DICOM output path.
        preview_path: Preview artifact path.
        seed: Run seed for traceability and reproducible placement.
        rotation_degrees: Shared rotation applied to the visible overlays.
        example_type: Example family such as ``echo``.
        font_size_pct: Font size as a percentage of the default (100 = default).
        placement_mode: ``"corners"`` picks a random corner; ``"free"`` picks a
            fully random position within the image.

    Returns:
        Prototype render result payload for the orchestrator.
    """
    del output_path
    del example_type
    _validate_rotation(rotation_degrees)
    if placement_mode not in _VALID_PLACEMENT_MODES:
        raise ValueError(
            f"placement_mode must be one of {_VALID_PLACEMENT_MODES}, got {placement_mode!r}."
        )

    font_size_px = _resolve_font_size_px(font_size_pct)
    rng = random.Random(seed)

    pixel_array = np.asarray(ds.pixel_array)
    frame_count = int(pixel_array.shape[0]) if pixel_array.ndim == 4 else 1
    annotations = _materialize_positions(
        visible_injections,
        extract_preview_frame(ds),
        font_size_px=font_size_px,
        placement_mode=placement_mode,
        rng=rng,
    )

    if pixel_array.ndim == 4:
        output_array = np.array(pixel_array, copy=True)
        output_array[0], _ = _render_frame_with_annotations(
            pixel_array[0], annotations, font_size_px=font_size_px
        )
    else:
        output_array, _ = _render_frame_with_annotations(
            pixel_array, annotations, font_size_px=font_size_px
        )

    preview_image, rendered_annotations = render_annotations_for_dataset(
        ds, annotations, font_size_px=font_size_px
    )
    preview_file = save_preview_image(preview_image, preview_path)

    _write_pixel_array(ds, output_array)
    box_annotations = []
    for rendered in rendered_annotations:
        box_annotations.append(
            {
                "label": rendered["label"],
                "text": rendered["text"],
                "region": rendered["region"],
                "corners": rendered["corners"],
                "rotation_degrees": rendered["rotation_degrees"],
                "frame_index": 0,
                "font_size_pct": font_size_pct,
            }
        )

    return {
        "dataset": ds,
        "status": "rendered",
        "preview_file": str(preview_file),
        "box_annotations": box_annotations,
        "render_metadata": {
            "seed": seed,
            "rotation_degrees": rotation_degrees,
            "allowed_rotations_degrees": list(ALLOWED_ROTATIONS_DEGREES),
            "frame_count": frame_count,
            "applied_frame_indices": [0],
            "visible_annotations": rendered_annotations,
        },
    }


def _render_single_annotation(
    base_image: Image.Image,
    annotation: dict[str, Any],
    font: ImageFont.ImageFont | ImageFont.FreeTypeFont,
) -> tuple[Image.Image, dict[str, Any]]:
    text = str(annotation["text"])
    position = _coerce_position(annotation["position"])
    rotation = int(annotation.get("rotation_degrees", 0))
    _validate_rotation(rotation)

    padding = int(annotation.get("padding", 4))
    fill = tuple(annotation.get("fill", (255, 255, 255)))
    stroke_fill = tuple(annotation.get("stroke_fill", (0, 0, 0)))
    stroke_width = int(annotation.get("stroke_width", 1))

    left, top, right, bottom = font.getbbox(text)
    text_width = max(1, right - left)
    text_height = max(1, bottom - top)
    base_width = text_width + (padding * 2)
    base_height = text_height + (padding * 2)

    text_layer = Image.new("RGBA", (base_width, base_height), (0, 0, 0, 0))
    drawer = ImageDraw.Draw(text_layer)
    drawer.text(
        (padding - left, padding - top),
        text,
        font=font,
        fill=fill,
        stroke_width=stroke_width,
        stroke_fill=stroke_fill,
    )

    rotated_layer = text_layer.rotate(rotation, expand=True, resample=Image.BICUBIC)
    composed = base_image.convert("RGBA")
    composed.alpha_composite(rotated_layer, dest=position)

    corners = _rotated_corners(
        position=position,
        unrotated_size=(base_width, base_height),
        rotated_size=rotated_layer.size,
        rotation_degrees=rotation,
    )

    record = {
        "label": annotation.get("label", "visible_text"),
        "text": text,
        "region": annotation.get("region", "top_left_overlay"),
        "rotation_degrees": rotation,
        "corners": corners,
        "render_metadata": {
            "position": {"x": position[0], "y": position[1]},
            "font_name": getattr(font, "path", "PillowDefaultFont"),
            "font_size": getattr(font, "size", None),
            "padding": padding,
            "fill_rgb": list(fill),
            "stroke_fill_rgb": list(stroke_fill),
            "stroke_width": stroke_width,
            "text_box_size": {"width": base_width, "height": base_height},
            "rotated_box_size": {
                "width": rotated_layer.size[0],
                "height": rotated_layer.size[1],
            },
        },
    }
    return composed.convert("RGB"), record


def _render_frame_with_annotations(
    frame: np.ndarray,
    annotations: list[dict[str, Any]],
    font_size_px: int = _DEFAULT_FONT_SIZE_PX,
) -> tuple[np.ndarray, list[dict[str, Any]]]:
    preview_image, rendered_annotations = render_visible_annotations(
        frame, annotations, font_size_px=font_size_px
    )
    return np.asarray(preview_image), rendered_annotations


def _materialize_positions(
    visible_injections: list[dict[str, Any]],
    frame: np.ndarray,
    font_size_px: int = _DEFAULT_FONT_SIZE_PX,
    placement_mode: str = "corners",
    rng: random.Random | None = None,
) -> list[dict[str, Any]]:
    if rng is None:
        rng = random.Random(0)

    image_height, image_width = frame.shape[:2]
    h_margin = max(24, int(image_width * 0.03))
    v_margin = max(24, int(image_height * 0.03))
    vertical_gap = max(10, int(image_height * 0.015))
    padding = 4
    font = load_default_font(font_size_px=font_size_px)

    sizes: list[tuple[int, int, int, int]] = []
    for injection in visible_injections:
        text = str(injection["text"])
        rotation = int(injection.get("rotation_degrees", 0))
        left, top, right, bottom = font.getbbox(text)
        base_w = max(1, right - left) + (padding * 2)
        base_h = max(1, bottom - top) + (padding * 2)
        rot_w, rot_h = _estimate_rotated_size(
            width=base_w, height=base_h, rotation_degrees=rotation
        )
        sizes.append((base_w, base_h, rot_w, rot_h))

    positioned_annotations: list[dict[str, Any]] = []

    if placement_mode == "corners":
        corner = rng.choice(["top_left", "top_right", "bottom_left", "bottom_right"])

        if corner in ("bottom_left", "bottom_right"):
            total_height = (
                sum(rot_h for _, _, _, rot_h in sizes)
                + vertical_gap * max(0, len(sizes) - 1)
            )
            current_y = max(v_margin, image_height - v_margin - total_height)
        else:
            current_y = v_margin

        for injection, (_, _, rot_w, rot_h) in zip(visible_injections, sizes):
            if corner in ("top_right", "bottom_right"):
                x = max(h_margin, image_width - h_margin - rot_w)
            else:
                x = h_margin
            positioned_annotations.append(
                {
                    **injection,
                    "position": (x, current_y),
                    "region": corner,
                    "padding": padding,
                    "stroke_width": 1,
                }
            )
            current_y += rot_h + vertical_gap

    elif placement_mode == "free":
        for injection, (_, _, rot_w, rot_h) in zip(visible_injections, sizes):
            x_max = max(h_margin, image_width - rot_w - h_margin)
            y_max = max(v_margin, image_height - rot_h - v_margin)
            x = rng.randint(h_margin, x_max)
            y = rng.randint(v_margin, y_max)
            positioned_annotations.append(
                {
                    **injection,
                    "position": (x, y),
                    "region": "free",
                    "padding": padding,
                    "stroke_width": 1,
                }
            )

    return positioned_annotations


def _estimate_rotated_size(
    *,
    width: int,
    height: int,
    rotation_degrees: int,
) -> tuple[int, int]:
    radians = math.radians(rotation_degrees)
    cosine = abs(math.cos(radians))
    sine = abs(math.sin(radians))
    rotated_width = int(math.ceil((width * cosine) + (height * sine)))
    rotated_height = int(math.ceil((width * sine) + (height * cosine)))
    return rotated_width, rotated_height


def _write_pixel_array(ds: pydicom.Dataset, output_array: np.ndarray) -> None:
    contiguous = np.ascontiguousarray(output_array)
    ds.PixelData = contiguous.tobytes()
    if contiguous.ndim == 4:
        ds.NumberOfFrames = contiguous.shape[0]
        ds.Rows = contiguous.shape[1]
        ds.Columns = contiguous.shape[2]
        ds.SamplesPerPixel = contiguous.shape[3]
    elif contiguous.ndim == 3 and contiguous.shape[-1] in {3, 4}:
        ds.Rows = contiguous.shape[0]
        ds.Columns = contiguous.shape[1]
        ds.SamplesPerPixel = contiguous.shape[2]
    else:
        ds.Rows = contiguous.shape[0]
        ds.Columns = contiguous.shape[1]
        ds.SamplesPerPixel = 1

    if contiguous.ndim >= 3 and contiguous.shape[-1] in {3, 4}:
        ds.PhotometricInterpretation = "RGB"
        ds.PlanarConfiguration = 0

    ds.file_meta.TransferSyntaxUID = ExplicitVRLittleEndian
    ds.is_implicit_VR = False
    ds.is_little_endian = True


def _coerce_position(position: Any) -> tuple[int, int]:
    if not isinstance(position, (tuple, list)) or len(position) != 2:
        raise ValueError("Annotation position must be a tuple/list with two items.")
    return int(position[0]), int(position[1])


def _validate_rotation(rotation_degrees: int) -> None:
    if rotation_degrees not in ALLOWED_ROTATIONS_DEGREES:
        raise ValueError(
            "Rotation must be one of "
            f"{ALLOWED_ROTATIONS_DEGREES}, got {rotation_degrees}."
        )


def _rotated_corners(
    position: tuple[int, int],
    unrotated_size: tuple[int, int],
    rotated_size: tuple[int, int],
    rotation_degrees: int,
) -> list[dict[str, float]]:
    width, height = unrotated_size
    rotated_width, rotated_height = rotated_size

    original_center = (width / 2.0, height / 2.0)
    rotated_center = (rotated_width / 2.0, rotated_height / 2.0)
    radians = math.radians(rotation_degrees)
    cosine = math.cos(radians)
    sine = math.sin(radians)

    base_corners = [
        (0.0, 0.0),
        (float(width), 0.0),
        (float(width), float(height)),
        (0.0, float(height)),
    ]
    rotated_corners: list[dict[str, float]] = []

    for x_value, y_value in base_corners:
        translated_x = x_value - original_center[0]
        translated_y = y_value - original_center[1]
        rotated_x = (translated_x * cosine) - (translated_y * sine)
        rotated_y = (translated_x * sine) + (translated_y * cosine)
        final_x = position[0] + rotated_center[0] + rotated_x
        final_y = position[1] + rotated_center[1] + rotated_y
        rotated_corners.append({"x": round(final_x, 2), "y": round(final_y, 2)})

    return rotated_corners
